version: '3'
services:
  core:
    build: .
    network_mode: host
    container_name: CheckFlow
    environment:
      DOUNAI_NAME: ${DOUNAI_NAME}
      DOUNAI_PWD: ${DOUNAI_PWD}
      WECOM_KEY: ${WECOM_KEY}
    volumes:
      - /etc/timezone:/etc/timezone:ro
